### ISSUE TITLE
Make available on conda-forge?

### ISSUE THREAD

**Issue by johnomotani** [diegojromerolopez/gelidum#15]
It would be nice to make `gelidum` available through [conda-forge](https://conda-forge.org/) - I personally prefer to manage the dependencies of my own package with conda, and would like `gelidum` to be available there so I can use it easily. I'm happy to set up the 'feedstock'. Maintenance after that is usually pretty easy. When a new version appears on PyPi, conda-forge will pick it up and automatically create an update. A line or two might need editing if the dependencies change, but other than that you just need to click 'merge' to release the new version on conda-forge.

@diegojromerolopez would it be OK for me to go ahead and add `gelidum` to conda-forge?

**Comment by diegojromerolopez** [comment]
I haven't used conda-forge, looks interesting.

Sure go ahead and add this package if you like. Thank you.

**Comment by diegojromerolopez** [comment]
@johnomotani anything else regarding this issue or it can be closed?

**Comment by johnomotani** [comment]
@diegojromerolopez it's done now! `gelidum` is available through conda-forge :smiley:

**Comment by diegojromerolopez** [comment]
All right, thank you!
